# Generated by Django 3.2b1 on 2021-03-10 09:53

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(django.db.models.functions.text.Lower('first_name'), django.db.models.expressions.OrderBy(django.db.models.functions.text.Upper('last_name'), descending=True), name='first_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('height'), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('weight'), '+', django.db.models.expressions.Value(5))), name='calc_idx'),
        ),
    ]
